site_name: pylastfmapi
repo_url: https://github.com/theorangewill/pylastfmapi
repo_name: theorangewill/pylastfmapi
edit_uri: tree/main/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Light mode

markdown_extensions:
  - attr_list
  - pymdownx.blocks.admonition
  - pymdownx.details
  - pymdownx.superfences

# extra_css:
#   - 'stylesheets/extras.css'

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [pylastfmapi]
